### ISSUE TITLE
LFS usage

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#1]
Thanks for [the doc](../tree/master/doc/git-lfs.md) on LFS @twdragon, I tried and added the [webinar recording](../tree/master/WP1/20200715-EOSC-Onboarding-Presentation/) using LFS, your use cases helped and it seems to have worked fine :crossed_fingers:.
 
A question though, what happens if someone clones the repo without installing LFS? It will not download the actual files but otherwise work seemlessly, right?

**Comment by twdragon** [comment]
@servansod that is the following situation: if your client supports external URL downloading (mostly the modern clients do), you will probably download actual data, but if not, ot if the server side hooks were blocked, you will have impostor files instead of actual data. All other functions in Git will work properly as they should do.

**Comment by twdragon** [comment]
@servansod should I explain this in the instruction?

**Comment by servansod** [comment]
Maybe you could just add a disclaimer if we have contributors not using the CLI, only to explain that LFS is useful when you clone or pull the repo because it avoids you downloading every single version of the files that ever existed so it is much quicker. And saying it is seamless if you don't have it installed but that it is advisable if we plan to upload large files (and revise them).

**Comment by twdragon** [comment]
Ok, I will do

**Comment by twdragon** [comment]
@servansod but I will also mention that acceleration of cloning depends from server setup, so LFS can not prevent from  downloading of all blobs in the repository by default.

**Comment by twdragon** [comment]
Closed with commit ID cb9fa5a
