### ISSUE TITLE
EU periodic report due 28.04.2021

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#11]
## Periodic reporting (directly in EU portal)
Task | Resp. | Progress | Target date | Comments or links
-|-|-|-|-
Summary for publication | Sophie | Finalising | 27.04.2021 | [Work in progress in this doc](https://docs.google.com/document/d/1X2yr7I8FcQIpRRzkajg1yTlNdkFj53wgrEx14Fllgh4/edit?usp=sharing) to be pasted to EU portal - WP2 :heavy_check_mark: WP3 :heavy_check_mark: WP4 :x: WP5 :x: WP6 :x:
Deliverables | Sophie | :heavy_check_mark: | - | From continuous reporting
Milestones| Sophie | :heavy_check_mark: | - | From continuous reporting
Critical risks | Valentina / Sophie | :heavy_check_mark: | - |
Publications | - | :heavy_check_mark: | | N/A
Dissemination | Kat | Almost finished | 27.04.2021 | See dedicated tab in [ExPaNDS KPIs](https://dlsltd.sharepoint.com/:x:/r/sites/GRA0046/Shared%20Documents/Project/ExPaNDS_KPIs.xlsx?d=w0c4ce0bbfe944f7dadd68bdf94af80ca&csf=1&web=1&e=bcS55l)
Patents | - | :heavy_check_mark: | | N/A
Open Data | - | :heavy_check_mark: | | N/A
Gender | Each facility's project office | :heavy_check_mark:  | | 
Financial statement | Each facility's project office | :heavy_check_mark:  | 27.04.2021 | To be included in report 

## Technical report (part B)
[Work in progress in this doc](https://docs.google.com/document/d/1_Qwm0dFVRw87ur0eJF0kynwM89VtNFmWCqcWWDaU6sg/edit?usp=sharing) - to be converted as .pdf and uploaded to the portal.
Chapter | Resp. | Progress | Target date | Comments
-|-|-|-|-
|1. Executive summary | Patrick | Not started :warning: | 27.04.2021 |
1.1 Objectives | Sophie | :heavy_check_mark: | 27.04.2021 | WP2 :heavy_check_mark: WP3 :heavy_check_mark: WP4 :x: WP5 :x: WP6 :x:
1.2.1 WP1 work | Sophie | :heavy_check_mark: | |
1.2.2 WP2 work | Brian / Abigail | Finalising | 27.04.2021 | see few comments left 
1.2.3 WP3 work | Alun | :heavy_check_mark: | |
1.2.4 WP4 work | Anton | :heavy_check_mark: |
1.2.5 WP5 work | Thibaud | Missing parts :warning:  | 27.04.2021
1.2.6 WP6 work | Kat | Finalising | 27.04.2021 | adding pictures
1.3 Impact | Sophie | :heavy_check_mark:  | - | 
|2. Update for the plan for dissemination | Sophie | :heavy_check_mark: | - | Isabelle to check
|3. Update of the DMP | Sophie | :heavy_check_mark: | - | 
5.1 deviation in deliverables and milestones | Sophie | Finalising | 27.04.2021 | User meeting replacement missing :warning: 
5.2 deviation in tasks | Sophie | In progress | 27.04.2021 | To be reviewed / completed by Anton :warning: 
5.3 deviation in use of resources | Sophie | Finalising | 27.04.2021 | Soleil plan missing for WP4 <br>WP2 :heavy_check_mark:  WP3 :heavy_check_mark: WP4 :x: WP5 :x: WP6 :x:

**Comment by wiggle120** [comment]
RE technical report (Part B), I've added a small bit of info to section 1.2.2 (WP2 work).  thanks, abigail

**Comment by servansod** [comment]
Thanks Abigail, and thanks for editing the comment. What needs to be done still is to break this down **for each beneficiary**. That can be a bit tricky. For WP2 it is ALBA, Elettra, HZB, PSI, Soleil and you UKRI (+in-kind from other whenever relevant).

**Comment by servansod** [comment]
Report just submitted :+1:
