### ISSUE TITLE
PaNOSC / ExPaNDS annual meeting 2021 organisation

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#12]
ExPaNDS and PaNOSC agreed to have the next annual meeting jointly again in 2021. The minutes of the organisational committee are recorded here.

**Comment by servansod** [comment]
## 2021.05.05
:raising_hand: :raising_hand_man:   Alun, Valentina, Patrick, Andy, Jordi, Sophie, Nicoletta, Kat

We are preparing for a **face-to-face event in PSI**, assuming no social distancing.
- Date range: week from **1st to 5th Nov. 2021** (W44), back-up from 25th to 29th Oct. 2021 (but MAX IV UM)
- Duration: **3 days noon-to-noon** + 1 day optional
- Room requirements: 2 large rooms simultaneously, incl. auditorium
- **Remote participation** possible on best effort basis (if we can travel, coordinators will encourage people to come in person)
- Switch to remote at any time?
- **Programme** ideas:
  - Users illustrating a PaN EOSC use case ("success story")
  - participation of another cluster project
  - WP day with possible breakout rooms (at least 2: technical + policies)

**Action list** for next meeting:
- [ ] Check facility available during week 44 (or week 43) 2021
- [ ] Set up Indico page
- [ ] Guidelines for accommodation / public transportation
- [ ] Set up recurring meeting for 2nd Wed. of the month

Next meeting: 9th of June, 15:00 CEST

**Comment by RKrahl** [comment]
Please note that [International Data Week 2021 including RDA 18th Plenary Meeting](https://www.rd-alliance.org/plenaries/rda-18th-plenary-meeting-part-international-data-week-2021-8%E2%80%9311-november-2021-seoul-south) takes place on 8th to 11th November 2021 in Seoul, South Korea, with co-located supposed to start on 6th Nov. That means that if we are able to travel at all by then, some people (including me) will not be available from 1st to 5th Nov.

Already the last annual meeting clashed with RDA VP16 which was very unfortunate.

**Comment by servansod** [comment]
## 2021.06.09
:raising_hand: :raising_hand_man:   Alun, Valentina, Patrick, Andy, Jordi, Sophie, Nicoletta, Kat

- Date range: PSI not available for the week from 1st to 5th Nov. 2021 (solving @RKrahl comment). The facility would be able to host us from **25th to 28th of October** though (the availability of the auditorium on the 29th still needs to be confirmed). Because of the LEAPS plenary (Barcelona, 20-22/10) and the MAX IV UM, we aim to have the AM as late in the week as possible. 
- Switch to remote - decision to be taken around end of August
- **Programme** drafting (similar as last year):
  - 1st half day: a bit more formal / plenaries / users talks / other clusters (all-hands)
  - 2nd day: WP day - to be shaped with WP leaders (in groups)
  - 3rd half day: final discussions and wrap-up (all-hands)
- on the side:
  - offer tours of PSI before / after the event?
  - poster session for clusters / 5b projects / use cases - 1st day evening
  - working dinner in the city - 2nd day evening
- Indico page: to be linked

**Action list** for next meeting:
- [ ] PSI to confirm final dates: 26-27-28/10 or 27-28-29/10?
- [ ] Send the save the date

Next meeting: TBC

**Comment by servansod** [comment]
## 2021.07.14
:raising_hand: :raising_hand_man:   Alun, Valentina, Patrick, Sophie, Nicoletta, Kat

### Date and format
- Dates are now confirmed: **26th to 28th of October**
- Possible formats (_reminder: decision end of August_)
  - 100% remote using Zoom
  - F2F with live-streaming for symposium part only 
Experience shows that at many facilities still, the conferencing tools in meeting rooms are usually bad, so we would like to avoid a "hybrid" mode. _Side remark: which doesn't exclude side local events as suggested previously_.

### Symposium - 1st half day
Several **external speaker ideas** were discussed and would now need approval from Andy, Rudolf and Jordi before being contacted:
- EOSC-Life with Susan Daenke > Brian
- EOSC-Future with Ron Dekker > Patrick
- [Petr Čermák as user ambassador](https://www.panosc.eu/news/interview-with-pan-user-petr-cermak-on-the-benefits-of-open-data-and-open-science/) > Nicoletta
- LEAPS representative > Valentina
- LENS representative ILL > Nicoletta?

Another topic we would like to address in this first 1/2 day would be concrete examples for users, with demos of VISA, simulation, choosing a few use cases. To be double-checked with Andy and Fabio/Anton.

**Audience targets** for this day: us + European Commission **+ users** so we should find a good balance between showcasing a) the successful collaborations and b) the actual results for our PaN communities.

### Next steps
- [Draft the **save the date**](https://docs.google.com/document/d/1IaOShkEM1o6LPuSgxDc4Ov-N5AQ1O8KBjpl9UxIevzc/edit?usp=sharing) using last year's template, to be sent around by the end of the month so people at least book the dates
- Work on the [programme in the Indico](https://indico.psi.ch/event/11435/) - Valentina gave access to all committee
- Set an **extra meeting before end of July** to agree on external speakers and save the date

**Comment by servansod** [comment]
From Jordi - copy of e-mail from 15.07.2021
> Just to let you know my thoughts about the Symposium (1st half day).
> 
> It seems to me that we want to address three different things:
> 1. Collaboration with other clusters
> 1. Sustainability and relationship with LEAPS/LENS
> 1. User engagement
> 
> I believe that point 3 is by far the most important and that **it would be beneficial to focus on the users** (at least for half of the afternoon). If each partner in PaNOSC and ExPaNDS can get 5 or 6 scientists/users to attend, we could be talking to ~100 of them and show them what tools are out there that they can use and how they can make a difference for their research. **We should show them what tools are already available / to be available in the very short term to keep them engaged.**
> 
> The remaining available time of the Symposium could be used for short presentations to cover points 1 and 2 which from my perspective not as important.
> 
> We risk having a Symposium that does not make a difference by trying to reach an audience too diverse and spreading ourselves thin on many separate topics.

**Comment by NicolettaCarboni** [comment]
Following various email exchanges and the PaNOSC PMC meeting on 21.07.2021, I report below the main outcomes of the discussion:

>> if we collect, e.g. 10 use cases, to be presented in brief talks of 10 min. each, we could cover almost 2 hours presenting concrete examples to the user community. PaNOSC WP leaders have been asked to select the use cases which are ready for the scope. Use cases may be presented taking into account the benefit of the related software/services to specific research domains, if we are able to cover enough of them. 

Feedback from Andy: 
>> EOSC-Life. It makes sense to involve them, if there has been progress to report on, otherwise there is a risk it is a repeat of the talk of last year. A new speaker like Carole Goble may be involved [https://www.software.ac.uk/about/staff/person/carole-goble] to speak about software and training in EOSC-Life.
>> In addition to Petr Cermak, a user from ESRF, Gianluca Santoni, may be invited to speak about COVID-19 research and how they will use PaNOSC resources for this 
>> Mousumi Upadhyay Kahaly (ELI-ALPS) may be one of the presenters of a use case. Here is the one published by Mousumi not long ago: https://www.panosc.eu/use-cases/panosc-use-case-18-in-silico-neutron-diffraction-from-boro-carbon-systems-precise-and-reliable-tool-for-exact-structural-analysis-and-defect-detection/

Feedback from Rudolf on EOSC-Future talk: to make the talk interesting for the user community, we may invite (e.g., 2) users who could provide inputs on what is still missing and could be useful for the PaN community of users doing interdisciplinary research. If may be good to have people from the EC in the audience to listen to such feedback.

My comment:
>> Two use cases which refer to software which are already available for the users are those about [fidviewer](https://www.panosc.eu/use-cases/panosc-use-case-19-online-visualization-and-analysis-of-bruker-nmr-output/) and [xrffitvis](https://www.panosc.eu/use-cases/panosc-use-case-21-online-visualization-and-analysis-of-hdf5-pymca-output-files/) 
fidviewer is related to NMR. It may still be presented, as NMR is complementary to PaN techniques.

>> LENS talk (Input from Jean-François and Stuart):
If on technical aspects, Paolo Mutti from ILL could act as representative of LENS. He is in charge of acquisition and software analysis development at ILL.
If on sustainability: Stuart Caunt (ILL) will ask at ILL who could represent LENS for this topic.

**Comment by NicolettaCarboni** [comment]
Speakers who confirmed their availability to give a talk at the PaNOSC-ExPaNDS symposium:
- Robert McGreevy (ISIS Director and LENS Chair) - Talk on LENS perspective on sustainability
and
- Petr Čermák - session on user engagement

**Comment by servansod** [comment]
## 2021.08.20
:raising_hand: :raising_hand_man:   Alun, Patrick, Isabelle, Andy, Jordi, Sophie, Kat

## Date and format
:warning: Decision for a **100% remote** event, **shortened to only the plenary talks of the first half-day (symposium)**.

Each WP can still decide to meet or not on days 2 and 3 but no "all-hands" will be kept in this virtual format. The experience of last year's AM shows that we would need real interaction for these days to be as successful and helpful as possible. Therefore we decided to **postpone the "all-hands" part of the annual meeting to spring / early summer 2022** with the hopes of having it F2F in Zürich.
As an online event, it was agreed to move the symposium to the morning, from 9:30 to 13:00 (Central Europe).

- [ ] send an updated save-the-date explaining this decision - Kat, Nicoletta by ~mid Sept.
- [ ] pick up planning of F2F all-hands around Jan. 2022

## Symposium programme
Taking previous comments into account, here is what was suggested for the agenda:
- Session 1 on projects **outcomes and sustainability** model, with contributions from LEAPS and LENS chairs (90 min)
- Session 2 on **use cases**, 3 x 15 min per project (90 min)
- [x] update [Indico](https://indico.psi.ch/event/11435/manage/timetable/#20211026) with discussed agenda - Sophie
- [ ] continue looking for speakers / use cases - each project by end of Sept.

**Comment by k-roarty** [comment]
**2021.09.08**
### 
🙋 🙋‍♂️ Andy, Jordi, Sophie, Valentina & Kat

**Notes and taken during meeting:** 
-  revised "save the date" text with Isabelle / Nicoletta for review, will be shared wider for final review
-  Confirmation pending from LEAPS chair Caterina Biscari for attendance 
- LENS chair Robert McGreevy confirmed participation 
- discussion around official invitation requirement and if this is to be sent - Valentina to advise  
- use cases discussion: PaNOSC confirmed Petr Čermák from ILL -others to be finalised. ExPaNDS - Sophie advised one use case will be a Training use case from SOLEIL. KR advised that poll questions can be set up, but will need to be received by Friday 22nd October to ensure set up in time. Unable to added once webinar is live. 
 
**Actions**: 
[ ] KR to share final revised safe the date text for team review ~ by Fri, 17 Sept.  
[ ] KR to set up ExPaNDS webinar meeting, to allow registration capturing of name, affiliation and job title ~ by end of this week.
[ ] KR / SS to review Indico page with Valentina ~ by Fri, 17 Sept. 
[ ] VP to advise on official invitation  ~ asap 
[ ] Poll questions - all ~ 22 Oct.

**Actions carried over from last meeting:** 
[ ] Finalise speakers / use cases for each project by end of Sept. (3 x use cases per project) 
[ ] pick up planning of F2F all-hands around Jan. 2022

Timings / Agenda: 
Time   (London) | Topic | Speaker
08:30 - 08:35 | Housekeeping | Kat Roarty
08:35 -   08:45 | Project overview | Patrick Fuhrmann /   Andy Goetz
08:45 -   09:05 | LEAPS overview | Caterina Biscari
09:05 -   09:25 | LENS overview | Robert McGreevy
09:25 -   09:45 | Q&A |  
09:45 - 10:00 | Coffee Break |  
10:00 -   10:10 | PaNOSC Use Case 1 | Petr Čermák from ILL
10:10 -   10:20 | PaNOSC Use Case 2 | TBC
10:20 -   10:30 | PaNOSC Use Case 3 | TBC
10:30 -   10:40 | ExPaNDS Use Case 1 | TBC
10:40 - 10:50 | ExPaNDS Use Case 2 | TBC
10:50 - 11:00 | ExPaNDS Use Case 3 | Training Use Case from SOLEIL
11:00 - 11:15 | Wrap up | Patrick Fuhrmann /   Andy Goetz

**Next meeting scheduled for the 27th September at 15:00 BST / 16:00 CEST.** 
https://diamondlight.zoom.us/j/94395801094?pwd=SG1zSHR0WVlvTXJVdTQvTXh0K3BuZz09 
Meeting ID: 943 9580 1094
Password: 252390

**Comment by servansod** [comment]
## 2021.09.29
:raising_hand: :raising_hand_man:  Alun, Isabelle, Kat, Nicoletta, Andy, Jordi, Sophie, Valentina

### Notes
- The **Indico page** is now publicly visible and updated with the preliminary agenda: [indico.psi.ch/event/11435/](https://indico.psi.ch/event/11435/).
- Use case speakers are being finalised on both sides.
- [Dissemination message](https://docs.google.com/document/d/17t76VZbb9pK6GT1il6sJmVBDE6i0ayuGfdEv1YVK9Tk/edit) ready to be sent to all tomorrow at the lastest :hourglass_flowing_sand:.
- The **chairs** for the 2 sessions will be Patrick and Andy. They will catch-up separately to prepare the introduction talk.
- The event is hosted in **Zoom at Diamond**.

### Actions
- [ ] Amend PaNOSC use cases names in Indico to make them more explicit (even if not final) and add speaker names when already know @NicolettaCarboni
- [ ] Same for ExPaNDS use cases @k-roarty
- [ ] Add the European flag and mention to our grants in the overview page @k-roarty
- [ ] Change the title to make it more visible / pretty - possibly including Nicoletta's banner **Valentina**
- [ ] Contact LENS chair to discuss the expected topic of his talk, using the questionnaire sent to LEAPS members @NicolettaCarboni 
- [ ] Same for the LEAPS chair **Valentina**
- [ ] Draft an invitation letter for LEAPS and LENS chairs including these "expectations" @k-roarty 
- [ ] Brief use case speakers to make them explicitly link their talks to ExPaNDS/PaNOSC outcomes @NicolettaCarboni, @k-roarty, **Isabelle**
- [ ] Draft an invitation letter for use case speakers including these "expectations" @servansod
- [ ] Ask PSI senior management to give the welcoming words **Alun**
- [ ] Send around the updated save-the-date to all channels **see list in google doc**

### Next meeting
Next meeting scheduled for the **8th of October at 12am BST / 1pm CEST**. Kat will send the invitation.

**Comment by NicolettaCarboni** [comment]
The event's announcement was made public on social media and sent to all internal PaNOSC stakeholders, subscribers to our mailing list info@panosc.eu, partners in comms WP for wider dissemination at their facilities and users, user offices of all PaN RIs in Europe, CERIC partners (Elettra, Budapest Neutron Centres, Rudjer Boskovic Institute, TUGraz, Surphace Physics group at Charles University, Solaris Synchrotron, National Institute of Materials Physics in Romania, National Institute of Chemistry in Slovenia), ESUO representatives. 

All PaNOSC speakers (Petr Cermak, Mousumi Upadhyay Kahaly and Yue Sun, were contacted and asked for the title + abstract of their presentation to be delivered possibly within Monday. It was also asked to make reference, in their presentations, to how FAIR data provided by PaNOSC are enabling these use cases. 

Robert Mc Greevy was contacted and asked to report on LENS position to the questions submitted to the LEAPS GA in his talk. 

The top banner in the indico page was updated.

**Comment by servansod** [comment]
Event and all final actions done.
