### ISSUE TITLE
Technical Architecture enhancements

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#16]
_Origin: Review Report PMOC-857641-1-RP1_

__Recommendation 1 (Technical Architecture Viewpoints and Architecture Validation – EOSC Integration Outlook):__
The technical architecture of the project must be analysed in more detail. 
Specifically, 
- information on the main processes and information flows across the various components must be provided. Likewise, 
- information on physical deployment and implementation must be added. 
- The architecture must be validated against PaN scenarios. 
- Relevant validation feedback should be received by stakeholders and taken into account to fine tune the architecture. 

Note that the integration of the project’s services in EOSC is seen as a longer term objective, which may also well happen beyond the end of the project.Therefore, the architecture should be checked and revised to fully take into account the project findings and detail the implementation.

Future documents could provide dynamic views of the architecture (e.g.,  information flows), while validating it in real-life integration scenarios.

Impacted document: [10.5281/zenodo.3697704](https://doi.org/10.5281/zenodo.3697704)

**Comment by martaguti** [comment]
Hi @servansod 

Thanks for this , I can take on this recommendation from the review. We can discuss the timeline later on today in our telco.
I may need some input from RI e.g. engagement with the stakeholders or the physical deployment planned

Marta

**Comment by martaguti** [comment]
1.  information on the main processes and information flows across the various components must be provided.    
__ACTION__: To be done by EGI (with the help and consensus of RI’s) 
2. information on physical deployment and implementation must be added. 
__QUESTION__:  would the information of the physical deployment represent the deployment achieved by each of the RI’s during the project lifetime or how the deployment is meant to be provided that everybody can fulfil all elements of the architecture?
3. The architecture must be validated against PaN scenarios.
__ACTION__: Validation of the architecture against use cases must be performed by the RI
4. Relevant validation feedback should be received by stakeholders and taken into account to fine tune the architecture.
__ACTION__: feedback should be taken by stakeholders. E.g stakeholders could be technical coordination board. ExPaNDS looking for a technical coordinator at the moment. (used to be Daniel @Alba)


__INPUTS__: Need input for 2,3 and 4 once 1 is ready and agreed by RI's
__OUTPUTS__: Review of Deliverable [D1.5 General Architecture description in relation to the EOSC services](https://zenodo.org/record/3697704#.YO6lgS1Q3T9)

**Comment by marauskajul** [comment]
The document has been uploaded to Zenodo:

[10.5281/zenodo.6958045](https://doi.org/10.5281/zenodo.6958045)

**Comment by marauskajul** [comment]
Relevant validation feedback was received by stakeholders (Nicolas S. and Uwe K.), who reviewed the document.
