### ISSUE TITLE
Data policy and metadata frameworks validation

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#17]
_Origin: Review Report PMOC-857641-1-RP1_

__Recommendation 2 (Data Policies and Metadata Framework Validation):__
A plan for validating and evaluating the project’s common data policy framework and the project’s metadata framework must be provided. This should include for example the number of policy workshops to be organized, the number of policy makers, Ris and scientists to be engaged etc.

**Comment by wiggle120** [comment]
Again, this is not an issue that should be assigned just to me - perhaps co-assign to Brian as well?  Thanks.

**Comment by servansod** [comment]
I might then need to add a new issue: "Getting Brian on GitHub". :innocent:

**Comment by wiggle120** [comment]
More generally, I'm not aware that we are planning any significant policy workshops in the second half of the project?  Certainly, it hasn't been something I've been aware of being discussed?  It feels like the data policy framework consultation was really the opportunity to speak with policy makers etc. at the various ExPaNDS facilities...

**Comment by brianmatthews42** [comment]
Consultation workshops for D2.3 covered detailed policy consultation.  Metadata workshop workshop on 1 March 2022 received feedback from partners to contribute to D2.7,

**Comment by marauskajul** [comment]
On 15/03/2022 we decided to close this issue.

**Comment by marauskajul** [comment]
This will be added to D2.9:

- the number of policy workshops to be organized
- the number of policy makers, RIs and scientists to be engaged

**Comment by brianmatthews42** [comment]
This recommendation has already been covered in previous deliverables.

 "validating and evaluating the project’s common data policy framework ... "

this was done exhaustively via detailed partner interviews in the development of D2.3.

"validating and evaluating the project’s common ... the project’s metadata framework"

This was done exhaustively via a partner workshop and other consultations in the development of D2.7.

**Comment by brianmatthews42** [comment]
D2.9 does not need to cover anything more for this recommendation.

**Comment by brianmatthews42** [comment]
WE said this in previous comments.  Can we finally close this.

**Comment by servansod** [comment]
Engagement of policy makers included in recently published [Report on promotion of FAIR data within Photon and Neutron RIs](https://doi.org/10.5281/zenodo.7572045).
