### ISSUE TITLE
Github.Pages content extraction

### ISSUE THREAD

**Issue by twdragon** [ExPaNDS-eu/ExPaNDS#2]
May I suggest to extract Github Pages content into the special directory instead of the Git branch? Now it seems quite inconvenient. To be honest, for this need I can strongly recommend creating the new project within our organization and then link it to our repository through `git submodule`

@servansod what do you think?

**Comment by servansod** [comment]
Hi Andrei, why is it inconvenient to keep the gh-pages branch exactly?

**Comment by twdragon** [comment]
@servansod from my point of view the branches store the different versions of some code, but not the completely different content. The branch may seem to be a good idea to store the content that should be 'hidden' for administrative purposes, but it stays editable for anyone who has permission to place commits. Also, the different project can allow us to build CI pipeline and obtain the prebuilt website without additional efforts and placement of generated content into the repository. To be honest, CI is what I want to investigate and deploy for us all, it could accelerate the preparation process significantly.

**Comment by servansod** [comment]
Fair enough, will do.

**Comment by servansod** [comment]
@twdragon the migration is complete, the branch deleted and you have rights for the other repo :+1:
