### ISSUE TITLE
Disclaimer when making deliverables that are not yet approved by the Commission public

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#28]
Following a remark from our PO: when we publish deliverables which are **not yet approved** by the European Commission, we need to add a disclaimer.

To be applied to:
- [x] [the Zenodo community](https://zenodo.org/communities/expands/): adding disclaimer "This deliverable is not yet approved by the European Commission." in the **`Additional notes`** field. To be removed once approved (done for PR1).
- [ ] [the website](https://expands.eu/deliverables/): agreed with @k-roarty to leave **only the approved deliverables** there.
- [x] [the public reporting page](https://expands-eu.github.io/WP1-reporting/deliverables.html): adding a deliverables **status** "Delivered and approved by the European Commission" or "Delivered but not yet approved by the European Commission"

**Comment by servansod** [comment]
Remaining task is only to add the following approved deliverables to the [expands.eu website](https://expands.eu/deliverables/):
- D1.8: [Periodic progress report](https://doi.org/10.5281/zenodo.4727980)
- D6.1: [Communication and Dissemination Plan](https://doi.org/10.5281/zenodo.4714675)
- D6.3: [Social media strategy](https://doi.org/10.5281/zenodo.4714909)
- D6.14: [Engage science communicators based at PAN RIs](https://doi.org/10.5281/zenodo.4714952)
- D6.19: [Assistance to the development of the taxonomy strategy for the relevant data catalogues](https://doi.org/10.5281/zenodo.4714999)

Then we can close this.

**Comment by k-roarty** [comment]
Website amended with missing items.
