### ISSUE TITLE
PDF documents are not FAIR

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#30]
**PDF files are not machine-readable** (especially the format used in Zenodo where links are even not clickable, for long-term stability) and text cannot be easily copied / reused by humans. However, that's been the format we have used to upload our deliverables in Zenodo so far. 

**Proposal**: from now on, all deliverables in Zenodo will be uploaded with .pdf **and native format in .odt**.

**Questions**:
- what about the previous deliverables? Is it worth making a new version to add the native format? The DOI will change.
- is .odt fine? even in cases where conversion is not perfect, it's better than putting .docx files right?
- alternative: link google doc in Zenodo metadata - but maybe not very persistent
- any other suggestion or objection? (e.g. IPR for branding)

**Comment by wiggle120** [comment]
Also to add to my comments copied above by Sophie, I would also say that .docx and similar aren't great from a security perspective either.  I agree with the point that Uwe makes about not touching those types of files when downloading (I think that is his point?)

**Comment by servansod** [comment]
So I talked to my librarian at DESY and he agrees [PDF/A](https://en.wikipedia.org/wiki/PDF/A) is acceptable for textual objects.
> In my opinion pdf/a is a good compromise, since at least some "dynamic" information (like links and copy&paste) is preserved - in contrast to storing documents as TIFF, which is another long term preservation standard.
> However an automatic conversion to pdf/a often fails, so in order to do that, the conversion should be done and checked before uploading.

In Zenodo, once files are downloaded, the links and copy-paste are indeed preserved, the limitations I noted seem to be only in the "preview" mode. __So we can give up the idea to add native files, it's not really useful.__ We can however do as he recommends and make the PDF/A conversion ourselves before uploading. This is in the options to export as PDF:
- in LibreOffice, checking "Archive (PDF/A, ISO 19005)" option 
- and apparently also in Word, checking the "PDF/A compatible" option.

PS: other interesting stuff he told me:
> - "Usual" PDF's with embedded fonts should also be fine for most practical purposes, provided there are no "exotic" things like Javascript, DRM, ... included. PDF/A ensures all that (and more), but I have seen only few files which really adhere to the standard. 
> - As far as I know Zenodo, which is based on INVENIO, converts pdfs to "pdf/a" using [openoffice/Ghostscript](https://ghostscript.com/doc/current/Readme.htm).
> - At the DESY Publication Database, which is also INVENIO based we rely on pdf's and automatically conversion to a pdf/a like format (as explained above), too. I expect that we have a lot more than 10 yrs for access. On our preprint servers we have files that are zipped Postscript files, which are still readable (and printable) after approx. 30 yrs. So even this format is not so bad. Avoid proprietary formats like doc, wps, .... LaTeX sources seems also to be fine, since arXiv uses this for more than 30yrs successfully.
