### ISSUE TITLE
Convincing senior management of the importance of FAIR

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#32]
During the CB meeting on the 17.11.2021, the issue was - again - raised that we need more discussions with our senior management on the **key FAIR aspects and their importance for our PaN facilities**.

One of the objectives is to make sure the **adoption of ExPaNDS and PaNOSC outputs, as committed to in the LEAPS survey, is taking place** and that data stewards are actually hired. We also want to contribute to making FAIR-related vocabulary more mainstream in PaN.

Some possible ways to achieve this (_to be discussed and completed_):
- [x] __1 on 1 discussions__ - e.g. as Brian suggested to do with Robert (LENS)
- [x] discussions triggered thanks to the preparation of the __senior level engagement deliverable__ (D6.24) - e.g. as happened with Christian Sch. for the promotional video
- [x] "peer pressure" __showcasing convinced directors__ (also linked to D6.24)
- [ ] getting more "outsiders" in the __CB__? (today it looks very much like the PEB)
- [x] #42

**Comment by twdragon** [comment]
I think, here the dissemination of the existing data stewards' responsibility lists could also help. Seeing them, we could develop arguments to motivate the management on understanding of the problems the data stewards are dealing with in the context of FAIR adoption. But here I still don't know how problematic it could be.

**Comment by marauskajul** [comment]
WP6 has done a senior level engagement, which can be found in [D6.24](https://doi.org/10.5281/zenodo.6924873). Interviews with facility member senior managers and directors have been accomplished.
