### ISSUE TITLE
Sponsorship of McXtrace training session at SOLEIL

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#37]
Proposal of WP5 to sponsor upcoming McXtrace training session at SOLEIL in March 2022. The idea would be to cover their travel expenses on ExPaNDS budget.

Good idea but Bea advised to clear this with the PO first so we are sure costs will be eligible. For this, we need to explain why it's important for the project that we support them. It can be either because they will spread the word on the platform or to support young scientists or something like that.

Ana suggested a [first version of the statement to the PO here](https://github.com/ExPaNDS-eu/ExPaNDS/blob/master/WP1/arguments-for-McXtrace-sponsorship.md). To be discussed with @patrickfuhrmann.

**Comment by servansod** [comment]
Following discussion with Patrick, I asked some more details to Ana (via email on the 21st of Feb) to complete the statement. I'll forward the thread if it's not solved before the 4th of March.

**Comment by marauskajul** [comment]
Patrick has received the approval of the PO (email, 12/04/2022):

Dear Ana,

I just received the approval of our PO for your McXtrace sponsorship.

However, he is reminding us that we have to provide detailed
descriptions/justifications in the technical report; also,
in case of a future amendment we have to include those as well.

Thanks and cheers
   -p.
