### ISSUE TITLE
Linking datasets to publication

### ISSUE THREAD

**Issue by paulmillar** [ExPaNDS-eu/ExPaNDS#45]
We have identified a use-case where a user who has used the pan-search-api to identified candidate datasets.  After identifying these datasets, the user then would like to see the list of publications that reference (or are otherwise based on) each of those datasets.

We believe this use-case is not part of the ExPaNDS DoW and this use-case is not supported by the ExPaNDS architecture.

However, we believe this use-case has merit and we would like to investigate whether others (the PaNOSC people, in particular) would be interested in some kind of future collaboration that would address this use-case.

**Comment by paulmillar** [comment]
You're right @RKrahl, this is non-trivial for several reasons.

Brian mentioned some existing work (Puma, if I remember the name correctly) that uses natural language processing to identify papers that are likely based on the dataset using the text from within the proposal description.

**Comment by mkubin** [comment]
Hi @paulmillar,
as pointed out by @RKrahl, there is some interesting overlap of your use-case with a project we are currently working on in [HMC Hub Matter](https://helmholtz-metadaten.de/en/matter/overview), where we identify datasets published by Helmholtz researchers. I think it could be fruitful to meet and exchange some ideas on the topic. Please feel free to [contact](hmc-matter@helmholtz-berlin.de) us. All best!

**Comment by twdragon** [comment]
It would be useful here to create an automated multilayered graph database connecting PIDs of datasets and publications. @RKrahl @zjttoefs @agbeltran have we the existing tools to build it?

**Comment by servansod** [comment]
Noting the idea and contacts for a possible OSCARS open call project or HMC open call. Closing this issue with ExPaNDS perspective though.
