### ISSUE TITLE
Sustainability sheets of PaN EOSC outcomes

### ISSUE THREAD

**Issue by servansod** [ExPaNDS-eu/ExPaNDS#51]
Sustainability sheets were initiated for each of the key outcomes of both ExPaNDS and PaNOSC:
https://docs.google.com/document/d/1O6GdwnJ4vTpT6-2_wsz-M_gdtYjF34aji2Pb2YxXUDU/edit?usp=sharing

Here to track progress and questions.

_Edition: status table moved to beginning of google doc_

The aim is to have all ExPaNDS-related sheets finalised for our final event in Hamburg :date: .

**Comment by servansod** [comment]
@hgoerzig thanks for your feedback. I have modified the document, separating the work around DMPs into 2 sections:
- DMP framework that I left almost empty, that would be the one to put what you suggest: template and general integration in the infrastructure
- DMP tool: DS-Wizard to keep what Marjolaine put for PaNOSC.

Let me know if that's fine.

Your participation is very welcome directly editing the document for the DMP framework sheet. If you have suggestions for the rest (metadata framework), please feel free to include them but in this case as comments/suggestions.

**Comment by hgoerzig** [comment]
@servansod Looks good. Thanks

**Comment by servansod** [comment]
Following preparation meeting from today 2023-01-13, I'm editing the list of outcomes:
- :heavy_plus_sign: Ontology API service added as new sheet
- :heavy_plus_sign: Nexus ontology added as new sheet
- :heavy_division_sign: FAIR data policy framework and FAIR self-assessment separated in 2 sheets

Also readjusting the order to have all ExPaNDS-related sheets at the beginning.

**Comment by servansod** [comment]
Following ExPaNDS closing event:
- :heavy_plus_sign: Testing and validation framework added - Sophie to discuss with Zdenek
- :heavy_check_mark: Comments / suggestions for WP2-related sheets  from discussions during sustainability meeting added 
- :hourglass_flowing_sand: WP2 will discuss how to finalise FAIR-related outcomes sheets next week for a possible final version by 2023-02-17 (Brian)
- :hourglass_flowing_sand: Comments / suggestions for WP3- and WP4-related sheets  from discussions during sustainability meeting to be added ASAP (Sophie)

**Comment by servansod** [comment]
First sheet is published: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7684470.svg)](https://doi.org/10.5281/zenodo.7684470)
Comments on the sheet or on the zenodo metadata welcome!

Others will follow in the next few days...

**Comment by UweKonrad** [comment]
That looks pretty good +1!

**Comment by servansod** [comment]
Closing with the publication of the last sheet.
Complete list can be found in [expands.eu](https://expands.eu/outcomes/).
:partying_face:
